name: hello world
on:
 push: 
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps: 
     - run: echo "hello"
     - run: echo "world"
     - name: Delete GitHub Actions cache
       uses: ramsyed123/delete-action-cache@main
 
